_wandb:
    value:
        cli_version: 0.21.0
        e:
            bahefsf0u51fbirxh109at31wev7lo36:
                codePath: gsm8k/willgist.py
                codePathLocal: willgist.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "269427478528"
                        used: "242953129984"
                email: jashvira2001404@gmail.com
                executable: /home/jash404/RL_experiments/.venv/bin/python
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-500eb3c2-4bed-a25a-7ddc-0764339fc499
                host: ADL-DSK-106
                memory:
                    total: "16737591296"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
                program: /home/jash404/RL_experiments/gsm8k/willgist.py
                python: CPython 3.11.12
                root: /home/jash404/RL_experiments/gsm8k
                startedAt: "2025-07-31T12:56:58.104711Z"
                writerId: bahefsf0u51fbirxh109at31wev7lo36
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
                - 100
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.12
            "5": 0.21.0
            "6": 4.53.3
            "8":
                - 1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 512
model_name:
    value: base-model-compiled
